#Container Setup for Development
  version: '2'

  # Named volumes
  volumes:
    #Redis Data
    otp-redis-data:
      driver: local

  services:
    # Caching
    cache:
      image: redis:4.0
      container_name: otp-redis
      command: --appendonly yes
      volumes:
        - otp-redis-data:/data
      ports:
        - "6379:6379"

    # Application
    app:
      image: ambientum/php:7.3-nginx
      container_name: otp-app
      volumes:
        - .:/var/www/app
      ports:
        - "80:8080"
      environment:
        - XDEBUG_ENABLED=true

    assets:
      image: ambientum/node:11
      container_name: otp-assets
      command: npm run watch
      volumes:
        - .:/var/www/app
